HEART_UPPER=100;
HEART_LOWER=60;
HEART_ZERO=0;

HEART_UPPER_ALERT="心率偏高";
HEART_LOWER_ALERT="心率偏低";
HEART_ALERT="无心跳";
HEART_NORMAL="心率正常";

BREATH_UPPER=20;
BREATH_LOWER=16;
BREATH_ZERO=0;
BREATH_NORMAL="呼吸正常";

BREATH_UPPER_ALERT="呼吸偏快";
BREATH_LOWER_ALERT="呼吸偏慢";
BREATH_ALERT="无呼吸";